name: autorun
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 18 * * 1'
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: 'test'
        type: boolean
        required: true
        default: true

jobs:
  autorun:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run code
        run: python3 run.py -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} -pr ${{ secrets.PROXY }}
